theme: cube

header:
  background: http://example.com/background.png
  title: senrenbankaの部落格


# if you use path, for example:
# background: background.png means that your
# should place your image(called "background.png")
# to the path "source/images/background.png"
background: http://example.com/background.png


# this variable is used to locate your background
# you know, on different devices, it have different view even if you use the same
# background, so it make your background display section instead of all the background
# for example, if you want to locate display your background from top
# you just need to type it: position: 0
position: 400


# this variable is used to make the background header being fuzzy
# if your do not need the filter blur on the top
# please make it empty, it means that: blur:
# if you do not understand it, then you can see my blog to find what mean it is
blur: 5

# yeah, this avatar is just make your avatar rounded or not
# if your want to have a rounded avatar, please make it true
avatar: true

menu:
  # index
  - title: 首页
    icon: home
    url: /
  # archives
  - title: 归档
    icon: archive
    url: archives
  # categories
  - title: 分类
    icon: categories
    url: categories
  # tags
  - title: 标签
    icon: tags
    url: tags
  # about-me
  - title: 关于我
    icon: about
    url: about-me

sidebar:
  links:
    - title: GitHub
      url: https://github.com/ZEROKISEKI
      # icon can be url or path(best is use cdn bucket url)
      icon: http://example.com//GitHub.png
    - title: Coding
      url: https://coding.net/u/SORA1
      icon: http://example.com/Coding.png
    - title: SF社区
      url: https://segmentfault.com/u/aonosora
      icon: http://example.com/SF.png
    - title: 开发者头条
      url: https://toutiao.io/u/148070
      icon: http://example.com/开发者头条.png
  friend_links:
    - title: 咪西西の部落格
      url: https://aonosora.com/
      # icon only url
      icon: http://example.com/micblo.png
    - title:
      url:
      icon:
      # if do not have icon, it will use friend_links
    - title:
      url:

# only path, refer to source/images
friend_links: friend_links.jpg

widgets:
- search
- author
- music
- recent_posts
- categories
- tagcloud
- links
- friend_links

search: true

# supported by DIYgod awesome project APlayer, you can find more on https://github.com/MoePlayer/APlayer
# and you can see the doc on https://aplayer.js.org/docs/#/
music_setting:
  auto: false
  mode: circulation
  narrow: false
  mutex: true
  # if you have the lrc file, make the `showlrc` true, else make it false
  showlrc: true
  theme:
  preload: auto
  maxHeight: 513px

# if you use path, make sure your hexo _config.yml has set the correcting url
# url: http://www.yoururl.com(notice it not allow to set it localhost)
# you'd better place your music and image, lrc to another site, and use url instead of path
# if you don't want to use this widget, just make that `music: `
music:
  - title: Dear friends
    author: TRIPLANE
    # source: path or url(path to source/music) for example, music1.mp3 refer to source/music/music1.mp3
    source: http://example.com/TRIPLANE - Dear friends.mp3
    # lrc: path or url(path to source/lrc) for example, music1.lrc refer to source/lrc/music1.lrc
    lrc: http://example.com/Dear friends - TRIPLANE.lrc
    # image: path or url(path to source/images/music) for example, music1.png refer to source/images/music/music1.png
    image: http://example.com/TRIPLANE - Dear friends.jpg
  - title:
    author:
    source:
    lrc:
    image:
  - title:
    author:
    source:
    lrc:
    image:

# before using the comment
# make use you know how to set the params
comment:
  disqus:
  changyan:
    appid:
    conf:
  youyan:
  # gitment: https://github.com/imsun/gitment
  # blog: https://imsun.net/posts/gitment-introduction/
  # make sure you know how to set it
  gitment:
    owner:
    repo:
    oauth:
      client_id:
      client_secret:

# some setting about comment module
comment_setting:
  changyan:
    hide_notice: true

analytics:
  baidu: #hash
  google: #hash